bundle/nxrm-operator-certified.v3.22.1.clusterserviceversion.yaml, deploy/olm-catalog/nxrm-operator-certified/3.22.1/nxrm-operator-certified.v3.22.1.clusterserviceversion.yaml, helm-charts/sonatype-nexus/Chart.yaml
Adrian found the emails we were previously using to be incorrect.
=> use better email address

build/Dockerfile, deploy/crds/sonatype.com_v1alpha1_nexusrepo_cr.yaml, deploy/olm-catalog/nxrm-operator-certified/3.23.0-1/nxrm-operator-certified.v3.23.0-1.clusterserviceversion.yaml, deploy/olm-catalog/nxrm-operator-certified/nxrm-operator-certified.package.yaml, deploy/operator.yaml, helm-charts/sonatype-nexus/Chart.yaml, helm-charts/sonatype-nexus/values.yaml
NXRM 3.23 was just released.  This is what needs to change each time there's a release. This will be fun to automate.
=> upgrade to nxrm 3.23

build/Dockerfile, deploy/olm-catalog/nxrm-operator-certified/3.24.0-1/nxrm-operator-certified.v3.24.0-1.clusterserviceversion.yaml, deploy/olm-catalog/nxrm-operator-certified/nxrm-operator-certified.package.yaml, deploy/operator.yaml
Baby step of upgrading the operator to ship NXRM 3.24.0. It doesn't actually require review, but I wanted to do it in a separate piece anyway before continuing on to jenkins work. someday, this will hopefully turn into some automated template work.
JIRA: https://issues.sonatype.org/browse/INT-2543
=> INT-2543 upgrade to latest nxrm 3.24.0

Jenkinsfile, README.md, ci/TriggerRedHatBuild.groovy, deploy/crds/sonatype.com_v1alpha1_nexusrepo_cr.yaml, deploy/olm-catalog/nxrm-operator-certified/3.24.0-7/nxrm-operator-certified.v3.24.0-7.clusterserviceversion.yaml, deploy/olm-catalog/nxrm-operator-certified/nxrm-operator-certified.package.yaml, deploy/operator.yaml, helm-charts/sonatype-nexus/Chart.yaml, helm-charts/sonatype-nexus/values.yaml
add a jenkins build to create the bundle and trigger a redhat build.
JIRA: https://issues.sonatype.org/browse/INT-2543
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/operator-nxrm3/job/feature-snapshots/job/INT-2543-jenkins/
Demo: https://drive.google.com/file/d/1TAcH6519XZ8PXZS6mx4OP8rogOciRW6a/view?usp=sharing
=> INT-2543 jenkins builds

build/Dockerfile, deploy/crds/sonatype.com_v1alpha1_nexusrepo_cr.yaml, deploy/olm-catalog/nxrm-operator-certified/3.25.0-1/nxrm-operator-certified.v3.25.0-1.clusterserviceversion.yaml, deploy/olm-catalog/nxrm-operator-certified/nxrm-operator-certified.package.yaml, deploy/operator.yaml, deploy/role.yaml, helm-charts/sonatype-nexus/Chart.yaml, helm-charts/sonatype-nexus/templates/NOTES.txt, helm-charts/sonatype-nexus/templates/additional-service.yaml, helm-charts/sonatype-nexus/templates/deployment-statefulset.yaml, helm-charts/sonatype-nexus/templates/service.yaml, helm-charts/sonatype-nexus/values.yaml
Update operator with latest changes from helm charts:
* cluster ip
* fixed terminate grace period
Also update to NXRM 3.25.0.
JIRA: https://issues.sonatype.org/browse/INT-3122
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/operator-nxrm3/job/feature-snapshots/job/INT-3122-update-chart/
=> INT-3122 update chart

scripts/new_version.sh, scripts/templates/Chart.yaml, scripts/templates/Dockerfile, scripts/templates/nxrm-operator-certified.package.yaml, scripts/templates/nxrm-operator-certified.vX.X.X-X.clusterserviceversion.yaml, scripts/templates/operator.yaml, scripts/templates/sonatype.com_v1alpha1_nexusrepo_cr.yaml, scripts/templates/values.yaml
I don't want to need to carefully update the operator for every new version of the server.
=> Template new version

build/Dockerfile, deploy/crds/sonatype.com_v1alpha1_nexusrepo_cr.yaml, deploy/olm-catalog/nxrm-operator-certified/3.25.1-1/nxrm-operator-certified.v3.25.1-1.clusterserviceversion.yaml, deploy/olm-catalog/nxrm-operator-certified/nxrm-operator-certified.package.yaml, deploy/operator.yaml, helm-charts/sonatype-nexus/Chart.yaml, helm-charts/sonatype-nexus/values.yaml
used the cool template script! pretty soon, these will *really* not be worth reviewing, since it's getting to be super-automatic.
JIRA: https://issues.sonatype.org/browse/INT-3280
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/operator-nxrm3/job/feature-snapshots/job/INT-3280-upgrade-to-3.25.1/
=> INT-3280 upgrade to 3.25.1

build/Dockerfile, deploy/crds/sonatype.com_v1alpha1_nexusrepo_cr.yaml, deploy/olm-catalog/nxrm-operator-certified/3.26.0-1/nxrm-operator-certified.v3.26.0-1.clusterserviceversion.yaml, deploy/olm-catalog/nxrm-operator-certified/nxrm-operator-certified.package.yaml, deploy/operator.yaml, helm-charts/sonatype-nexus/Chart.yaml, helm-charts/sonatype-nexus/values.yaml
Nothing too interesting. plain scripted update.
JIRA: https://issues.sonatype.org/browse/INT-3307
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/operator-nxrm3/job/feature-snapshots/job/INT-3307-upgrade-nxrm-3.26.0/
=> upgrade for nxrm 3.26.0

build/Dockerfile, deploy/crds/sonatype.com_v1alpha1_nexusrepo_cr.yaml, deploy/olm-catalog/nxrm-operator-certified/3.27.0-1/nxrm-operator-certified.v3.27.0-1.clusterserviceversion.yaml, deploy/olm-catalog/nxrm-operator-certified/nxrm-operator-certified.package.yaml, deploy/operator.yaml, helm-charts/sonatype-nexus/Chart.yaml, helm-charts/sonatype-nexus/values.yaml
build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/operator-nxrm3/job/feature-snapshots/job/INT-3452-upgrade-3.27.0/
jira: https://issues.sonatype.org/browse/INT-3452
=> Upgrade to nxrm 3.27.0

build/Dockerfile, deploy/crds/sonatype.com_v1alpha1_nexusrepo_cr.yaml, deploy/olm-catalog/nxrm-operator-certified/3.28.0-1/nxrm-operator-certified.v3.28.0-1.clusterserviceversion.yaml, deploy/olm-catalog/nxrm-operator-certified/nxrm-operator-certified.package.yaml, deploy/operator.yaml, helm-charts/sonatype-nexus/Chart.yaml, helm-charts/sonatype-nexus/values.yaml
JIRA: https://issues.sonatype.org/browse/INT-3588
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/operator-nxrm3/job/feature-snapshots/job/INT-3588-upgrade-3.28.0/
=> upgrade to 3.28.0

deploy/olm-catalog/nxrm-operator-certified/3.28.1-1/nxrm-operator-certified.v3.28.1-1.clusterserviceversion.yaml, scripts/bundle.sh
Script the process for producing and pushing an operator bundle to Red Hat.
JIRA: https://issues.sonatype.org/browse/INT-4424
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/operator-nxrm3/job/feature-snapshots/job/INT-4424-bundling/ (broken for bundle.sh changes. will be fixed in separate ci story)
=> INT-4424 operator bundle

deploy/olm-catalog/nxrm-operator-certified/3.28.1-1/nxrm-operator-certified.v3.28.1-1.clusterserviceversion.yaml, scripts/templates/nxrm-operator-certified.vX.X.X-X.clusterserviceversion.yaml
eliminate confusion and set better expectations.
=> doc: HA-C unsupported

Jenkinsfile
simple maintenance, so merging immediately.
=> INT-4438 update latest jenkins libs

Jenkinsfile, README.md, scripts/templates/Dockerfile
First step: catch up small fixes to ensure the operator deploys that we learned with IQ Operator.
JIRA: https://issues.sonatype.org/browse/INT-4102 (part 1)
Jenkins: https://jenkins.ci.sonatype.dev/view/all/job/integrations/job/cloud/job/operator-nxrm3/job/feature-snapshots/job/INT-4102-release-latest/
=> INT-4102 fixes for deployment

build/Dockerfile, deploy/crds/sonatype.com_v1alpha1_nexusrepo_cr.yaml, deploy/olm-catalog/nxrm-operator-certified/3.30.0-1/nxrm-operator-certified.v3.30.0-1.clusterserviceversion.yaml, deploy/olm-catalog/nxrm-operator-certified/nxrm-operator-certified.package.yaml, deploy/operator.yaml, helm-charts/sonatype-nexus/Chart.yaml, helm-charts/sonatype-nexus/values.yaml
Upgrade to deploy NXRM 3.30.0
JIRA: https://issues.sonatype.org/browse/INT-4102
Jenkins: https://jenkins.ci.sonatype.dev/view/all/job/integrations/job/cloud/job/operator-nxrm3/job/feature-snapshots/job/INT-4102-nxrm-3.30.0/
=> INT-4102 upgrade to 3.30.0

build/Dockerfile, deploy/olm-catalog/nxrm-operator-certified/3.31.1-2/nxrm-operator-certified.v3.31.1-2.clusterserviceversion.yaml, deploy/olm-catalog/nxrm-operator-certified/nxrm-operator-certified.package.yaml, deploy/operator.yaml, scripts/templates/Dockerfile
upgrade helm-operator base image to alleviate red hat security violations.
=> INT-5337 newer operator image

Jenkinsfile
* Adjusting Jenkinsfile for default branch migration
Ticket: https://issues.sonatype.org/browse/INT-5496
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/operator-nxrm3/
=> INT-5496 Default Branch Migration - RedHat Operator - NXRM

scripts/templates/Chart.yaml, scripts/templates/nxrm-operator-certified.package.yaml, scripts/templates/nxrm-operator-certified.vX.X.X-X.clusterserviceversion.yaml, scripts/templates/operator.yaml, scripts/templates/sonatype.com_v1alpha1_nexusrepo_cr.yaml, scripts/templates/values.yaml
operators are now required to have certain yaml formatting enforced by yamllint.
https://issues.sonatype.org/browse/INT-6258
=> INT-6258 fixes from yamllint

README.md, scripts/templates/nxrm-operator-certified.clusterserviceversion.yaml, scripts/templates/sonatype.com_v1alpha1_nexusrepo_cr.yaml, scripts/templates/values.yaml
Use the correct environment variable for memory settings, and update them to the minimum recommended.
JIRA: https://issues.sonatype.org/browse/INT-6622
Build: N/A
=> INT-6622 correct mem settings

scripts/templates/nxrm-operator-certified.clusterserviceversion.yaml
Updating docs to add Operator Installation Suggestion to handle unscheduled downtime due to new operator releases.
JIRA: https://issues.sonatype.org/browse/INT-6772
=> INT-6772 Adding Operator Intallation Suggestion

scripts/bundle.sh, scripts/templates/annotations.yaml
ready for openshift 4.12 in december 2022: adjust version declaration
JIRA: https://issues.sonatype.org/browse/INT-7026
Build: N/A
=> INT-7026 allow next operator on openshift 4.10+

helm-charts/sonatype-nexus/templates/deployment-statefulset.yaml, scripts/templates/operator.yaml
set seucurity context for the new versions of k8s and openshift.
JIRA: https://issues.sonatype.org/browse/INT-7432
=> INT-7432 set security context for newer k8s/openshift

scripts/templates/Dockerfile
JIRA: https://issues.sonatype.org/browse/INT-7478
=> INT-7478 upgrade to operator-helm 1.25.2

build/Dockerfile, helm-charts/sonatype-nexus/Chart.yaml, helm-charts/sonatype-nexus/values.yaml
https://sonatype.atlassian.net/browse/NEXUS-39680
=> NEXUS-39680 - Upgrade repo version

deploy/crds/sonatype.com_v1alpha1_nexusrepo_cr.yaml, deploy/olm-catalog/nxrm-operator-certified/nxrm-operator-certified.package.yaml, deploy/operator.yaml
=> Nexus 39680 Update operator image urls for 3.57.0-01

deploy/olm-catalog/nxrm-operator-certified/3.57.0-1/manifests/nxrm-operator-certified.clusterserviceversion.yaml, deploy/olm-catalog/nxrm-operator-certified/3.57.0-1/manifests/sonatype.com_nexusrepos_crd.yaml, deploy/olm-catalog/nxrm-operator-certified/3.57.0-1/metadata/annotations.yaml, scripts/templates/nxrm-operator-certified.clusterserviceversion.yaml
Generated metadata and manifests for Nexus Repository 3.57.0-1 Open shift operator
The outcome of running ./scripts/new_version.sh bundle 3.57.0-1  `<operator-image-url> <app-image-url>`
=> Manifests and metadata for version 3.57.0-1

deploy/olm-catalog/nxrm-operator-certified/3.57.0-1/manifests/nxrm-operator-certified.clusterserviceversion.yaml, scripts/templates/Dockerfile, scripts/templates/nxrm-operator-certified.clusterserviceversion.yaml
Add related images section to clusterserviceversion yaml as per https://github.com/redhat-openshift-ecosystem/certification-releases/blob/main/4.9/ga/troubleshooting.md#digest-pinning in an attempt to fix https://github.com/redhat-openshift-ecosystem/certified-operators/pull/2565
=> Nexus 39680 - update repo version to 3.57

deploy/olm-catalog/nxrm-operator-certified/3.57.0-1/manifests/nxrm-operator-certified.clusterserviceversion.yaml, scripts/templates/nxrm-operator-certified.clusterserviceversion.yaml
Fill in spec.relatedImages section as advised by red hat
The files in this PR were generated by following instructions on the page at: https://sonatype.atlassian.net/wiki/spaces/INT/pages/23490779/Development+Guide+for+IBM+Red+Hat+Operators#DevelopmentGuideforIBM%2FRedHatOperators-NXRM3
=> Nexus-39680 update repo version to 3.57
